version: '3'

services:
  db:
    image: mysql:8.0
    volumes:
      - data-store:/var/lib/mysql
    environment:
      - MYSQL_USER: root
      - MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
